### ISSUE TITLE
How to activate my tabtab object?

### ISSUE THREAD

**Issue by Gavin-YYC** [mklabs/node-tabtab#37]
First I installed tabtab, in accordance with the requirements of the document:

```
npm install tabtab --save
```

Then, I created a new file named: program:

```
#! /usr/bin/env node

// Ex. bin/ entry point for a "program" package
var tab = require('tabtab')({
  name: 'program'
});

// General handler. Gets called on `program <tab>` and `program stuff ... <tab>`
tab.on('program', function(data, done) {
  // General handler
  done(null, ['foo', 'bar']);
});

// Specific handler. Gets called on `program list <tab>`
tab.on('list', function(data, done) {
  done(null, ['file.js', 'file2.js']);
});

// Start must be called to register the completion commands and listen for
// completion.
tab.start();
```

I think the effect should be,I type "program" and then press the tab key will automatically appear "foo" and "bar" two options.

But I do't know what to do next to produce the above effect.

I followed the document to continue:

```
. <(tabtab install --stdout --name program)
```

But suggested tabtab order not found...

System：mac os

**Comment by mklabs** [comment]
Hi @Gavin-YYC 

No you have to install tabtab globally (with npm -g) in order to be able to use the tabtab program (in your `. <(tabtab install --stdout --name program)` line)

But that's not how tabtab is designed to be used. I recommend checking some packages that uses tabtab to see some example. You have to rely on tabtab in your package.json and then have an install script in this same file to trigger the `tabtab install --auto`.

The example you described and tested is meant to be within one of your package, which is then installed globally.
